name: CI

on: [pull_request, workflow_dispatch]


jobs:
  precommit_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: python -m pip install -r requirements_dev.txt
      - name: Run black
        run: black --check .
      - name: Run isort
        run: isort --check .
      - name: Run flake8
        run: flake8 --statistics .

  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install Pytest
        run: python -m pip install pytest pytest-cov
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install TileDB-CF-Py
        run: python -m pip install ".[netCDF4,xarray,parallel]"
      - name: Test with coverage
        run: |
          python -m pytest --cov-report term-missing --cov-report=html:coverage --cov-report=xml:coverage/coverage.xml --cov="tiledb/cf"
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: coverage
