name: CI

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches: [ main, dev ]
    paths: [ '**.py' ]
  pull_request:
    branches: [ main, dev ]
    paths: [ '**.py' ]

jobs:
  precommit_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: python -m pip install black isort flake8 mypy
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run black
        run: black --check .
      - name: Run isort
        run: isort --check .
      - name: Run flake8
        run: flake8 --statistics .
      - name: Run mypy
        run: mypy .


  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Run Tox
        run: tox -e py
